server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: eventhub_admin
    password: eventhub_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true