spring:
  application:
    name: ticket-service
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active: dev
  kafka:
    consumer:
      group-id: ticket-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer